{{- if .Values.podGroupAssigner.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-group-assigner
  namespace: {{ .Release.Namespace }}
  labels:
    app: pod-group-assigner
    {{- include "kai-resource-management.labels" . | nindent 4 }}
{{- end }}
