//go:build !ignore_autogenerated

// Copyright 2026 NVIDIA CORPORATION
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/kai-scheduler/api/kai/v1/common"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalConfig) DeepCopyInto(out *GlobalConfig) {
	*out = *in
	if in.SchedulerName != nil {
		in, out := &in.SchedulerName, &out.SchedulerName
		*out = new(string)
		**out = **in
	}
	if in.QueueLabelKey != nil {
		in, out := &in.QueueLabelKey, &out.QueueLabelKey
		*out = new(string)
		**out = **in
	}
	if in.NodePoolLabelKey != nil {
		in, out := &in.NodePoolLabelKey, &out.NodePoolLabelKey
		*out = new(string)
		**out = **in
	}
	if in.FinalizerDomain != nil {
		in, out := &in.FinalizerDomain, &out.FinalizerDomain
		*out = new(string)
		**out = **in
	}
	if in.NamespaceProjectLabelKey != nil {
		in, out := &in.NamespaceProjectLabelKey, &out.NamespaceProjectLabelKey
		*out = new(string)
		**out = **in
	}
	if in.ProjectLabelKey != nil {
		in, out := &in.ProjectLabelKey, &out.ProjectLabelKey
		*out = new(string)
		**out = **in
	}
	if in.EnforceSchedulerAnnotationKey != nil {
		in, out := &in.EnforceSchedulerAnnotationKey, &out.EnforceSchedulerAnnotationKey
		*out = new(string)
		**out = **in
	}
	if in.ReplicaCount != nil {
		in, out := &in.ReplicaCount, &out.ReplicaCount
		*out = new(int32)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.PriorityClassName != nil {
		in, out := &in.PriorityClassName, &out.PriorityClassName
		*out = new(string)
		**out = **in
	}
	if in.Openshift != nil {
		in, out := &in.Openshift, &out.Openshift
		*out = new(bool)
		**out = **in
	}
	if in.Fips != nil {
		in, out := &in.Fips, &out.Fips
		*out = new(bool)
		**out = **in
	}
	if in.JSONLog != nil {
		in, out := &in.JSONLog, &out.JSONLog
		*out = new(bool)
		**out = **in
	}
	if in.VPA != nil {
		in, out := &in.VPA, &out.VPA
		*out = new(common.VPASpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalConfig.
func (in *GlobalConfig) DeepCopy() *GlobalConfig {
	if in == nil {
		return nil
	}
	out := new(GlobalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KRMConfig) DeepCopyInto(out *KRMConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KRMConfig.
func (in *KRMConfig) DeepCopy() *KRMConfig {
	if in == nil {
		return nil
	}
	out := new(KRMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KRMConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KRMConfigList) DeepCopyInto(out *KRMConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KRMConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KRMConfigList.
func (in *KRMConfigList) DeepCopy() *KRMConfigList {
	if in == nil {
		return nil
	}
	out := new(KRMConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KRMConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KRMConfigSpec) DeepCopyInto(out *KRMConfigSpec) {
	*out = *in
	if in.Global != nil {
		in, out := &in.Global, &out.Global
		*out = new(GlobalConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SchedulerConfigRef != nil {
		in, out := &in.SchedulerConfigRef, &out.SchedulerConfigRef
		*out = new(SchedulerConfigRef)
		**out = **in
	}
	if in.NodePoolController != nil {
		in, out := &in.NodePoolController, &out.NodePoolController
		*out = new(NodePoolController)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectController != nil {
		in, out := &in.ProjectController, &out.ProjectController
		*out = new(ProjectController)
		(*in).DeepCopyInto(*out)
	}
	if in.PodGroupAssigner != nil {
		in, out := &in.PodGroupAssigner, &out.PodGroupAssigner
		*out = new(PodGroupAssigner)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KRMConfigSpec.
func (in *KRMConfigSpec) DeepCopy() *KRMConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KRMConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KRMConfigStatus) DeepCopyInto(out *KRMConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KRMConfigStatus.
func (in *KRMConfigStatus) DeepCopy() *KRMConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KRMConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolController) DeepCopyInto(out *NodePoolController) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(common.Service)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.VPA != nil {
		in, out := &in.VPA, &out.VPA
		*out = new(common.VPASpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolController.
func (in *NodePoolController) DeepCopy() *NodePoolController {
	if in == nil {
		return nil
	}
	out := new(NodePoolController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupAssigner) DeepCopyInto(out *PodGroupAssigner) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(common.Service)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.VPA != nil {
		in, out := &in.VPA, &out.VPA
		*out = new(common.VPASpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupAssigner.
func (in *PodGroupAssigner) DeepCopy() *PodGroupAssigner {
	if in == nil {
		return nil
	}
	out := new(PodGroupAssigner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectController) DeepCopyInto(out *ProjectController) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(common.Service)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.VPA != nil {
		in, out := &in.VPA, &out.VPA
		*out = new(common.VPASpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectController.
func (in *ProjectController) DeepCopy() *ProjectController {
	if in == nil {
		return nil
	}
	out := new(ProjectController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerConfigRef) DeepCopyInto(out *SchedulerConfigRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerConfigRef.
func (in *SchedulerConfigRef) DeepCopy() *SchedulerConfigRef {
	if in == nil {
		return nil
	}
	out := new(SchedulerConfigRef)
	in.DeepCopyInto(out)
	return out
}
