//go:build !ignore_autogenerated

// Copyright 2026 NVIDIA CORPORATION
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/kai-scheduler/api/kai/v1/common"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteBlocker) DeepCopyInto(out *DeleteBlocker) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteBlocker.
func (in *DeleteBlocker) DeepCopy() *DeleteBlocker {
	if in == nil {
		return nil
	}
	out := new(DeleteBlocker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalConfig) DeepCopyInto(out *GlobalConfig) {
	*out = *in
	if in.SchedulerName != nil {
		in, out := &in.SchedulerName, &out.SchedulerName
		*out = new(string)
		**out = **in
	}
	if in.QueueLabelKey != nil {
		in, out := &in.QueueLabelKey, &out.QueueLabelKey
		*out = new(string)
		**out = **in
	}
	if in.NodePoolLabelKey != nil {
		in, out := &in.NodePoolLabelKey, &out.NodePoolLabelKey
		*out = new(string)
		**out = **in
	}
	if in.DefaultNodePoolName != nil {
		in, out := &in.DefaultNodePoolName, &out.DefaultNodePoolName
		*out = new(string)
		**out = **in
	}
	if in.FinalizerDomain != nil {
		in, out := &in.FinalizerDomain, &out.FinalizerDomain
		*out = new(string)
		**out = **in
	}
	if in.NamespaceProjectLabelKey != nil {
		in, out := &in.NamespaceProjectLabelKey, &out.NamespaceProjectLabelKey
		*out = new(string)
		**out = **in
	}
	if in.ProjectLabelKey != nil {
		in, out := &in.ProjectLabelKey, &out.ProjectLabelKey
		*out = new(string)
		**out = **in
	}
	if in.EnforceSchedulerAnnotationKey != nil {
		in, out := &in.EnforceSchedulerAnnotationKey, &out.EnforceSchedulerAnnotationKey
		*out = new(string)
		**out = **in
	}
	if in.ReplicaCount != nil {
		in, out := &in.ReplicaCount, &out.ReplicaCount
		*out = new(int32)
		**out = **in
	}
	if in.LeaderElection != nil {
		in, out := &in.LeaderElection, &out.LeaderElection
		*out = new(bool)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.RequireDefaultPodAntiAffinityTerm != nil {
		in, out := &in.RequireDefaultPodAntiAffinityTerm, &out.RequireDefaultPodAntiAffinityTerm
		*out = new(bool)
		**out = **in
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.PriorityClassName != nil {
		in, out := &in.PriorityClassName, &out.PriorityClassName
		*out = new(string)
		**out = **in
	}
	if in.Openshift != nil {
		in, out := &in.Openshift, &out.Openshift
		*out = new(bool)
		**out = **in
	}
	if in.FipsMode != nil {
		in, out := &in.FipsMode, &out.FipsMode
		*out = new(FipsMode)
		**out = **in
	}
	if in.JSONLog != nil {
		in, out := &in.JSONLog, &out.JSONLog
		*out = new(bool)
		**out = **in
	}
	if in.VPA != nil {
		in, out := &in.VPA, &out.VPA
		*out = new(common.VPASpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceMonitor != nil {
		in, out := &in.ServiceMonitor, &out.ServiceMonitor
		*out = new(ServiceMonitorSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalConfig.
func (in *GlobalConfig) DeepCopy() *GlobalConfig {
	if in == nil {
		return nil
	}
	out := new(GlobalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KRMConfig) DeepCopyInto(out *KRMConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KRMConfig.
func (in *KRMConfig) DeepCopy() *KRMConfig {
	if in == nil {
		return nil
	}
	out := new(KRMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KRMConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KRMConfigList) DeepCopyInto(out *KRMConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KRMConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KRMConfigList.
func (in *KRMConfigList) DeepCopy() *KRMConfigList {
	if in == nil {
		return nil
	}
	out := new(KRMConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KRMConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KRMConfigSpec) DeepCopyInto(out *KRMConfigSpec) {
	*out = *in
	if in.Global != nil {
		in, out := &in.Global, &out.Global
		*out = new(GlobalConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SchedulerConfigRef != nil {
		in, out := &in.SchedulerConfigRef, &out.SchedulerConfigRef
		*out = new(SchedulerConfigRef)
		**out = **in
	}
	if in.NodePoolController != nil {
		in, out := &in.NodePoolController, &out.NodePoolController
		*out = new(NodePoolController)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectController != nil {
		in, out := &in.ProjectController, &out.ProjectController
		*out = new(ProjectController)
		(*in).DeepCopyInto(*out)
	}
	if in.PodGroupAssigner != nil {
		in, out := &in.PodGroupAssigner, &out.PodGroupAssigner
		*out = new(PodGroupAssigner)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KRMConfigSpec.
func (in *KRMConfigSpec) DeepCopy() *KRMConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KRMConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KRMConfigStatus) DeepCopyInto(out *KRMConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KRMConfigStatus.
func (in *KRMConfigStatus) DeepCopy() *KRMConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KRMConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolController) DeepCopyInto(out *NodePoolController) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(common.Service)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.VPA != nil {
		in, out := &in.VPA, &out.VPA
		*out = new(common.VPASpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolController.
func (in *NodePoolController) DeepCopy() *NodePoolController {
	if in == nil {
		return nil
	}
	out := new(NodePoolController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupAssigner) DeepCopyInto(out *PodGroupAssigner) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(common.Service)
		(*in).DeepCopyInto(*out)
	}
	if in.ControllerService != nil {
		in, out := &in.ControllerService, &out.ControllerService
		*out = new(PodGroupAssignerService)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhooks != nil {
		in, out := &in.Webhooks, &out.Webhooks
		*out = new(PodGroupAssignerWebhooks)
		(*in).DeepCopyInto(*out)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = new(PodGroupAssignerArgs)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.VPA != nil {
		in, out := &in.VPA, &out.VPA
		*out = new(common.VPASpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupAssigner.
func (in *PodGroupAssigner) DeepCopy() *PodGroupAssigner {
	if in == nil {
		return nil
	}
	out := new(PodGroupAssigner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupAssignerArgs) DeepCopyInto(out *PodGroupAssignerArgs) {
	*out = *in
	if in.Debug != nil {
		in, out := &in.Debug, &out.Debug
		*out = new(bool)
		**out = **in
	}
	if in.LeaderElect != nil {
		in, out := &in.LeaderElect, &out.LeaderElect
		*out = new(bool)
		**out = **in
	}
	if in.UnexistingNodepoolSentinel != nil {
		in, out := &in.UnexistingNodepoolSentinel, &out.UnexistingNodepoolSentinel
		*out = new(string)
		**out = **in
	}
	if in.AnnotationNodepoolsKey != nil {
		in, out := &in.AnnotationNodepoolsKey, &out.AnnotationNodepoolsKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupAssignerArgs.
func (in *PodGroupAssignerArgs) DeepCopy() *PodGroupAssignerArgs {
	if in == nil {
		return nil
	}
	out := new(PodGroupAssignerArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupAssignerService) DeepCopyInto(out *PodGroupAssignerService) {
	*out = *in
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(PortMapping)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupAssignerService.
func (in *PodGroupAssignerService) DeepCopy() *PodGroupAssignerService {
	if in == nil {
		return nil
	}
	out := new(PodGroupAssignerService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupAssignerWebhooks) DeepCopyInto(out *PodGroupAssignerWebhooks) {
	*out = *in
	if in.EnablePodWebhook != nil {
		in, out := &in.EnablePodWebhook, &out.EnablePodWebhook
		*out = new(bool)
		**out = **in
	}
	if in.CertSecretName != nil {
		in, out := &in.CertSecretName, &out.CertSecretName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupAssignerWebhooks.
func (in *PodGroupAssignerWebhooks) DeepCopy() *PodGroupAssignerWebhooks {
	if in == nil {
		return nil
	}
	out := new(PodGroupAssignerWebhooks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortMapping) DeepCopyInto(out *PortMapping) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.TargetPort != nil {
		in, out := &in.TargetPort, &out.TargetPort
		*out = new(int32)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortMapping.
func (in *PortMapping) DeepCopy() *PortMapping {
	if in == nil {
		return nil
	}
	out := new(PortMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Profiling) DeepCopyInto(out *Profiling) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.APIPort != nil {
		in, out := &in.APIPort, &out.APIPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Profiling.
func (in *Profiling) DeepCopy() *Profiling {
	if in == nil {
		return nil
	}
	out := new(Profiling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectController) DeepCopyInto(out *ProjectController) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(common.Service)
		(*in).DeepCopyInto(*out)
	}
	if in.ControllerService != nil {
		in, out := &in.ControllerService, &out.ControllerService
		*out = new(ProjectControllerService)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhooks != nil {
		in, out := &in.Webhooks, &out.Webhooks
		*out = new(ProjectControllerWebhooks)
		(*in).DeepCopyInto(*out)
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(ProjectControllerFeatures)
		(*in).DeepCopyInto(*out)
	}
	if in.Profiling != nil {
		in, out := &in.Profiling, &out.Profiling
		*out = new(Profiling)
		(*in).DeepCopyInto(*out)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = new(ProjectControllerArgs)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraProjectRoleBindings != nil {
		in, out := &in.ExtraProjectRoleBindings, &out.ExtraProjectRoleBindings
		*out = make([]ProjectRoleBinding, len(*in))
		copy(*out, *in)
	}
	if in.RoleBindingsConfigMapName != nil {
		in, out := &in.RoleBindingsConfigMapName, &out.RoleBindingsConfigMapName
		*out = new(string)
		**out = **in
	}
	if in.DeleteBlockers != nil {
		in, out := &in.DeleteBlockers, &out.DeleteBlockers
		*out = make([]DeleteBlocker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.VPA != nil {
		in, out := &in.VPA, &out.VPA
		*out = new(common.VPASpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectController.
func (in *ProjectController) DeepCopy() *ProjectController {
	if in == nil {
		return nil
	}
	out := new(ProjectController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectControllerArgs) DeepCopyInto(out *ProjectControllerArgs) {
	*out = *in
	if in.Debug != nil {
		in, out := &in.Debug, &out.Debug
		*out = new(bool)
		**out = **in
	}
	if in.LeaderElect != nil {
		in, out := &in.LeaderElect, &out.LeaderElect
		*out = new(bool)
		**out = **in
	}
	if in.ProjectNamePrefix != nil {
		in, out := &in.ProjectNamePrefix, &out.ProjectNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.ProjectIDLabelKey != nil {
		in, out := &in.ProjectIDLabelKey, &out.ProjectIDLabelKey
		*out = new(string)
		**out = **in
	}
	if in.QueueDepartmentNameLabelKey != nil {
		in, out := &in.QueueDepartmentNameLabelKey, &out.QueueDepartmentNameLabelKey
		*out = new(string)
		**out = **in
	}
	if in.NamespaceVersionLabelKey != nil {
		in, out := &in.NamespaceVersionLabelKey, &out.NamespaceVersionLabelKey
		*out = new(string)
		**out = **in
	}
	if in.ResourceManualOverrideLabelKey != nil {
		in, out := &in.ResourceManualOverrideLabelKey, &out.ResourceManualOverrideLabelKey
		*out = new(string)
		**out = **in
	}
	if in.LimitRangeName != nil {
		in, out := &in.LimitRangeName, &out.LimitRangeName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectControllerArgs.
func (in *ProjectControllerArgs) DeepCopy() *ProjectControllerArgs {
	if in == nil {
		return nil
	}
	out := new(ProjectControllerArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectControllerFeatures) DeepCopyInto(out *ProjectControllerFeatures) {
	*out = *in
	if in.CreateNamespaces != nil {
		in, out := &in.CreateNamespaces, &out.CreateNamespaces
		*out = new(bool)
		**out = **in
	}
	if in.CreateRoleBindings != nil {
		in, out := &in.CreateRoleBindings, &out.CreateRoleBindings
		*out = new(bool)
		**out = **in
	}
	if in.ClusterWideSecret != nil {
		in, out := &in.ClusterWideSecret, &out.ClusterWideSecret
		*out = new(bool)
		**out = **in
	}
	if in.ClusterWideConfigMap != nil {
		in, out := &in.ClusterWideConfigMap, &out.ClusterWideConfigMap
		*out = new(bool)
		**out = **in
	}
	if in.ClusterWidePvc != nil {
		in, out := &in.ClusterWidePvc, &out.ClusterWidePvc
		*out = new(bool)
		**out = **in
	}
	if in.LimitRange != nil {
		in, out := &in.LimitRange, &out.LimitRange
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectControllerFeatures.
func (in *ProjectControllerFeatures) DeepCopy() *ProjectControllerFeatures {
	if in == nil {
		return nil
	}
	out := new(ProjectControllerFeatures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectControllerService) DeepCopyInto(out *ProjectControllerService) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(PortMapping)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(PortMapping)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectControllerService.
func (in *ProjectControllerService) DeepCopy() *ProjectControllerService {
	if in == nil {
		return nil
	}
	out := new(ProjectControllerService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectControllerWebhooks) DeepCopyInto(out *ProjectControllerWebhooks) {
	*out = *in
	if in.EnableProjectValidation != nil {
		in, out := &in.EnableProjectValidation, &out.EnableProjectValidation
		*out = new(bool)
		**out = **in
	}
	if in.EnableDepartmentValidation != nil {
		in, out := &in.EnableDepartmentValidation, &out.EnableDepartmentValidation
		*out = new(bool)
		**out = **in
	}
	if in.CertSecretName != nil {
		in, out := &in.CertSecretName, &out.CertSecretName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectControllerWebhooks.
func (in *ProjectControllerWebhooks) DeepCopy() *ProjectControllerWebhooks {
	if in == nil {
		return nil
	}
	out := new(ProjectControllerWebhooks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectRoleBinding) DeepCopyInto(out *ProjectRoleBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectRoleBinding.
func (in *ProjectRoleBinding) DeepCopy() *ProjectRoleBinding {
	if in == nil {
		return nil
	}
	out := new(ProjectRoleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerConfigRef) DeepCopyInto(out *SchedulerConfigRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerConfigRef.
func (in *SchedulerConfigRef) DeepCopy() *SchedulerConfigRef {
	if in == nil {
		return nil
	}
	out := new(SchedulerConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMonitorSpec) DeepCopyInto(out *ServiceMonitorSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMonitorSpec.
func (in *ServiceMonitorSpec) DeepCopy() *ServiceMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceMonitorSpec)
	in.DeepCopyInto(out)
	return out
}
