{{- if .Values.nodepoolController.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodepool-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: nodepool-controller
    {{- include "kai-resource-management.labels" . | nindent 4 }}
{{- end }}
