{{- if .Values.projectController.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: project-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: project-controller
    {{- include "kai-resource-management.labels" . | nindent 4 }}
{{- end }}
